### ISSUE TITLE
how do i easily test this?  

### ISSUE THREAD

**Issue by adriaanbalt** [jpodwys/prefetch#6]
how do i easily test this?  i assume i would be seeing something in my network tab?

also, does running Prefetch.init(); automatically find every <a href=""> tag and run this function?  or do i need to designate what it should look for?

**Comment by jpodwys** [comment]
I apologize, somehow I wasn't watching this repo so I missed this issue!

Yes, activity will show up in your network tab if prefetch is configured correctly.

As for running it in your project, you need to provide an array of CSS selectors, called "containers" in the [Basic Usage](https://github.com/jpodwys/prefetch#basic-usage) demo. Prefetch will attach delegate event listeners to all of the containers you specify. This makes it unnecessary to attach listeners to every single link on the page and also allows prefetch to listen for clicks on dynamically added links within the containers you specified.

[Here's an example](https://github.com/jpodwys/riot-progressive-enhancement/blob/master/assets/js/app.js#L93-L98) of a place I'm configuring prefetch in one of my own projects. (Please forgive the bloat in that repo. It was a tech playground where I tried lots of new things without much care for code cleanliness.)
